apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../../apps/pipeline/upstream/third-party/minio/base

patchesStrategicMerge:
- patch.yaml

- |-
  $patch: delete
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: minio-pvc

secretGenerator:
- name: mlpipeline-minio-artifact
  type: Opaque
  behavior: replace
  envs:
  - secret_params.env


